# Generated by Django 5.2.4 on 2025-08-01 21:44

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exhibits", "0022_alter_exhibitsorderable_options"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBExhibit",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("subheading", 0),
                            ("text", 1),
                            ("html", 2),
                            ("records", 12),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic"],
                                    "form_classname": "title",
                                    "icon": "title",
                                },
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "AAPB record IDs, separated by whitespace",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Special collections IDs",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show asset title(s) for this block",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show asset thumbnail(s) for this block",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Include title in sidebar",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic"],
                                    "help_text": "The title of this group",
                                    "max_length": 1024,
                                    "required": False,
                                },
                            ),
                            9: (
                                "ov_collections.blocks.DurationBlock",
                                (),
                                {
                                    "help_text": "Start time for the group",
                                    "required": False,
                                },
                            ),
                            10: (
                                "ov_collections.blocks.DurationBlock",
                                (),
                                {
                                    "help_text": "End time for the group",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("all", "All"),
                                        ("digitized", "Digitized"),
                                        ("online", "Online"),
                                    ],
                                    "help_text": "Access level for AAPB search links in this block",
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("guids", 3),
                                        ("special_collections", 4),
                                        ("show_title", 5),
                                        ("show_thumbnail", 6),
                                        ("show_sidebar", 7),
                                        ("title", 8),
                                        ("start_time", 9),
                                        ("end_time", 10),
                                        ("access_level", 11),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "AAPB Exhibit",
                "verbose_name_plural": "AAPB Exhibits",
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="AAPBExhibitsOrderable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exhibits.openvaultexhibit",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_exhibits",
                        to="aapb_exhibits.aapbexhibit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
