# Generated by Django 5.2.8 on 2025-12-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0002_aapbexhibit_display_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbexhibitsorderable",
            name="exhibit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="aapb_exhibits.aapbexhibit",
            ),
        ),
    ]
