# Generated by Django 5.2.8 on 2025-12-16 21:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0003_alter_aapbexhibitsorderable_exhibit"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBExhibitsChildOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aapb_exhibits.aapbexhibit",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_order",
                        to="aapb_exhibits.aapbexhibit",
                    ),
                ),
            ],
            options={
                "verbose_name": "AAPB Exhibit Child Order",
                "verbose_name_plural": "AAPB Exhibit Children Order",
            },
        ),
    ]
