# Generated by Django 5.2.8 on 2025-12-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0004_aapbexhibitschildorder"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AAPBExhibitsOrderable",
            new_name="AAPBOtherExhibits",
        ),
    ]
