# Generated by Django 5.2.8 on 2025-12-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0005_rename_aapbexhibitsorderable_aapbotherexhibits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aapbexhibitschildorder",
            options={
                "verbose_name": "AAPB Exhibit page",
                "verbose_name_plural": "AAPB Exhibit pages",
            },
        ),
    ]
