# Generated by Django 5.2.8 on 2025-12-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0006_alter_aapbexhibitschildorder_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbexhibitschildorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aapbotherexhibits",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
