# Generated by Django 5.2.8 on 2026-01-09 17:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0007_alter_aapbexhibitschildorder_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbexhibit",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("subheading", 0),
                    ("text", 1),
                    ("html", 2),
                    ("records", 12),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "form_classname": "title",
                            "icon": "title",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "help_text": "The title of this group",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "form_classname": "w-field--scrollable-textarea",
                            "help_text": "AAPB record IDs, separated by whitespace",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Special collections IDs", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset title(s) for this block",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset thumbnail(s) for this block",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Include title in sidebar",
                            "required": False,
                        },
                    ),
                    9: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "Start time for the group", "required": False},
                    ),
                    10: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "End time for the group", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("all", "All"),
                                ("digitized", "Digitized"),
                                ("online", "Online"),
                            ],
                            "help_text": "Access level for AAPB search links in this block",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("guids", 4),
                                ("special_collections", 5),
                                ("show_title", 6),
                                ("show_thumbnail", 7),
                                ("show_sidebar", 8),
                                ("start_time", 9),
                                ("end_time", 10),
                                ("access_level", 11),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
