# Generated by Django 5.2.11 on 2026-07-14 19:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "0011_aapbexhibittag_aapbexhibit_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbexhibit",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("subheading", 0),
                    ("text", 1),
                    ("html", 2),
                    ("records", 13),
                    ("vimeo", 16),
                    ("youtube", 17),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "form_classname": "title",
                            "icon": "title",
                        },
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "help_text": "The title of this group",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Optional thumbnail for the group. If not provided, the first record will be used as the thumbnail."
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "form_classname": "w-field--scrollable-textarea",
                            "help_text": "AAPB record IDs, separated by whitespace",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Special collections IDs", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset title(s) for this block",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset thumbnail(s) for this block",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Include title in sidebar",
                            "required": False,
                        },
                    ),
                    10: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "Start time for the group", "required": False},
                    ),
                    11: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "End time for the group", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("all", "All"),
                                ("digitized", "Digitized"),
                                ("online", "Online"),
                            ],
                            "help_text": "Access level for AAPB search links in this block",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("thumbnail", 4),
                                ("guids", 5),
                                ("special_collections", 6),
                                ("show_title", 7),
                                ("show_thumbnail", 8),
                                ("show_sidebar", 9),
                                ("start_time", 10),
                                ("end_time", 11),
                                ("access_level", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "The URL of the YouTube video", "required": True},
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "help_text": "The title of this video",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 14), ("title", 15)]],
                        {"label": "Vimeo"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 14), ("title", 15)]],
                        {"label": "YouTube"},
                    ),
                },
            ),
        ),
    ]
