version: '3.8'

services:
  wagtail:
    build:
      context: .
      target: production
    image: ov-wag
    volumes:
      - ./:/app/
    entrypoint: /app/docker_entrypoints/dev.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./db:/var/lib/postgresql/data:Z
    user: ${UID}:${GID}
    restart: always
