version: '3.8'

services:
  wagtail:
    build:
      context: .
      target: production
    # Use the `image` property to run a prebuilt image from GHCR instead of building locally. Requires disabling the `build` section above.
    # image: ghcr.io/wgbh-mla/ov-wag:main
    volumes:
      - ./:/app/
    entrypoint: /app/docker_entrypoints/dev.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${OV_DB_NAME}
      - POSTGRES_USER=${OV_DB_USER}
      - POSTGRES_PASSWORD=${OV_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  front:
    image: ov-front
    build:
      context: ../ov-frontend
      target: dev
    environment:
      - OV_API_URL=http://wagtail:8000
    volumes:
      - ../ov-frontend:/app
    ports:
      - 3000:3000
volumes:
  db:
