version: '3.8'

services:
  wagtail:
    build: .
    image: ov
    volumes:
      - ./:/app/
    working_dir: /app
    command:
      # - tail -f /dev/null
      # - python manage.py migrate --noinput
      # - gunicorn ov_wag.wsgi:application --reload
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    user: ${UID}:${GID}
    restart: always
