version: '3.8'

services:
  wagtail:
    build:
      context: .
      target: base
    image: ghcr.io/wgbh-mla/ov-wag:pr-76
    volumes:
      - ./:/app/
    entrypoint: /app/docker_entrypoints/dev.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
  db:
    image: postgres:14.2-alpine
    user: ${UID}:${GID}
    restart: always
