#!/bin/bash

if [ $1 = "dev" -o $1 = "d" ]; then
  shift
  docker run -itp 8000:8000 -v $(pwd)/:/app/ ov "$@"

elif [ $1 = "build" -o $1 = "b" ]; then
  shift
  docker build -t ov . "$@"

elif [ $1 = "shell" -o $1 = "s" ]; then
  shift
  docker run -it -v $(pwd)/:/app/ ov python3 manage.py shell "$@"

elif [ $1 = "manage" -o $1 = "m" ]; then
  shift
  docker run -it -v $(pwd)/:/app/ ov python3 manage.py "$@"

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  docker run -it ov "$@"

fi
