#!/bin/bash
HELP="Open Vault init script\n\n

USAGE:\n\n

  ./ov COMMAND [args] \n\n

COMMANDS:\n\n

\t  b | build \t  build the docker image\n
\t  c | cmd \t    run a bash command with the docker image\n
\t  d | dev \t    start a development server\n
\t  h | help \t   prints this help text\n
\t  s | shell \t  enter into a python shell with the app context\n
\t  t | test \t   run the wagtail test suite
\t  m | manage \t run a manage.py command
"

COMPOSE="docker compose -f docker-compose.yml"
DEV="-f dev.yml"
MANAGE="run wagtail python3 manage.py"

if [ -z $1 ]; then
  echo -e $HELP

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  # docker run -itp 8000:8000 -v $(pwd)/:/app/ ov "$@"
  $COMPOSE $DEV up

elif [ $1 = "build" -o $1 = "b" ]; then
  shift
  $COMPOSE build "$@"

elif [ $1 = "shell" -o $1 = "s" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py shell "$@"
  $COMPOSE $DEV $MANAGE shell "$@"

elif [ $1 = "manage" -o $1 = "m" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov python3 manage.py "$@"
  $COMPOSE $DEV $MANAGE "$@"

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  # docker run -it -v $(pwd)/:/app/ ov "$@"
  $COMPOSE $DEV run -it wagtail "$@"

elif [ $1 = "test" -o $1 = "t" ]; then
  shift
  # Run tests in isolation
  $COMPOSE run wagtail-tests

else echo -e $HELP

fi
