
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "ov-wag"
dependencies = ["Django<4.2,>=4.1.1", "wagtail<4.1,>=4.0.4", "wagtail-factories<3.2,>=3.1.0", "pydantic<2.0,>=1.10.2", "psycopg2<2.10,>=2.9.3"]
requires-python = ">=3.8"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
extend-exclude = 'migrations'

[tool.ruff]
extend-exclude = ['migrations']
ignore = ['Q000']
select = [
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'C90', # mccabe
    'E', # pycodestyle errors
    'ERA', # eradicate
    'F', # pyflakes
    # 'I', # isort
    'INT', # flake8-gettext
    'N', # pep8-naming
    'PIE', # flake8-pie,
    'PLC', # pylint - convention
    'PLE', # pylint - error
    'PLW', # pylint - warning
    'Q', # flake8-quotes
    'RET', # flake8-return,
    'RUF', # Ruff-specific rules
    'SIM', # flake8-simplify
    'UP', # pyupgrade
    'W', # pycodestyle warnings

]
[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.3",
]
test = [
    "pytest>=7.4.3",
    "pytest-django>=4.6.0",
    "pytest-cov>=4.1.0",
    "pytest-sugar>=0.9.7",
    "pytest-xdist>=3.3.1",
    "nbmake>=1.4.6",
]
