
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dependencies = ["Django<4.2,>=4.1.1", "wagtail<4.1,>=4.0.4", "wagtail-factories<3.2,>=3.1.0", "pydantic<2.0,>=1.10.2", "psycopg2<2.10,>=2.9.3"]
requires-python = ">=3.8"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
extend-exclude = 'migrations'
