
[project]
name = 'ov-wag'
dynamic = ['version']
description = 'WGBH Open Vault Wagtail backend'
authors = [{ name = 'WGBH-MLA', email = 'ryan_harbert@wgbh.org' }]
readme = 'README.md'
license = { text = 'MIT' }
dependencies = [
    'Django~=4.1',
    'wagtail~=4.0',
    'wagtail-factories~=3.1',
    'pydantic~=1.10',
    'psycopg2~=2.9',
    'python-dotenv~=1.0',
    'gunicorn~=21.2',
]
requires-python = '>=3.8,<4.0'

[project.urls]
documentation = 'https://wgbh-mla.github.io/ov-wag/'
homepage = 'https://github.com/WGBH-MLA/ov-wag'
repository = 'https://github.com/WGBH-MLA/ov-wag'


[project.scripts]
ov = 'cli:app'

[project.optional-dependencies]
cli = [
    "typer~=0.9",
    "loguru~=0.7",
    "trogon~=0.5",
]

[build-system]
requires = ['pdm-backend']
build-backend = 'pdm.backend'

[tool.pdm]
version = { source = 'file', path = 'ov_wag/_version.py' }

[tool.black]
extend-exclude = 'migrations'

[tool.pdm.dev-dependencies]
dev = [
    'pre-commit~=3.5',
]
test = [
    "pytest>=7.4.3",
    "pytest-django>=4.6.0",
    "coverage>=7.3.2",
]

[tool.pytest.ini_options]
testpaths = ['authos', 'exhibits', 'ov_collections', 'ov_wag', 'search']
DJANGO_SETTINGS_MODULE = 'ov_wag.settings.test'
