
[project]
name = 'ov-wag'
dependencies = [
    'Django~=4.2',
    'wagtail~=5.0',
    'wagtail-factories~=3.1',
    'pydantic~=1.10',
    'psycopg2~=2.9',
    'python-dotenv~=1.0',
    'gunicorn~=21.2',
]
requires-python = '>=3.8,<4.0'

[build-system]
requires = ['pdm-backend']
build-backend = 'pdm.backend'

[tool.black]
extend-exclude = 'migrations'

[tool.ruff]
extend-exclude = ['migrations']
ignore = ['Q000']
select = [
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'C90', # mccabe
    'E', # pycodestyle errors
    'ERA', # eradicate
    'F', # pyflakes
    # 'I', # isort
    'INT', # flake8-gettext
    'N', # pep8-naming
    'PIE', # flake8-pie,
    'PLC', # pylint - convention
    'PLE', # pylint - error
    'PLW', # pylint - warning
    'Q', # flake8-quotes
    'RET', # flake8-return,
    'RUF', # Ruff-specific rules
    'SIM', # flake8-simplify
    'UP', # pyupgrade
    'W', # pycodestyle warnings

]

[tool.pdm.dev-dependencies]
dev = [
    'ruff~=0.1',
    'pre-commit~=3.5',
]
test = [
    "pytest>=7.4.3",
    "pytest-django>=4.6.0",
    "pytest-cov>=4.1.0",
    "pytest-sugar>=0.9.7",
    "pytest-xdist>=3.3.1",
    "nbmake>=1.4.6",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'ov_wag.settings.test'
python_files = ['tests.py', 'test_*.py', '*_tests.py']
testpaths =[
  'authors',
  'exhibits',
  'ov_wag'
]