# Generated by Django 5.2.11 on 2026-06-23 17:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aapb_collections", "0010_alter_aapbcollection_content_and_more"),
        ("aapb_exhibits", "0010_alter_aapbexhibit_body"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBPrimarySourceSet",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("created_by", models.CharField(blank=True)),
                ("subjects", wagtail.fields.RichTextField(blank=True)),
                (
                    "pdf_link",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to the downloadable teaching-tips PDF.",
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                (
                    "teaching_tips",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Background info, essential question, discussion questions, and classroom activities.",
                    ),
                ),
                ("additional_resources", wagtail.fields.RichTextField(blank=True)),
                ("references", wagtail.fields.RichTextField(blank=True)),
                (
                    "sources",
                    wagtail.fields.StreamField(
                        [("records", 10)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic"],
                                    "max_length": 1024,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic", "bold"],
                                    "help_text": "For use in Primary Source Sets Only",
                                    "max_length": 1024,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "form_classname": "w-field--scrollable-textarea",
                                    "help_text": "AAPB record ID, separated by whitespace if providing multiple IDs",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Special collections IDs",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show asset title(s) for this block",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Show asset thumbnail(s) for this block",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Include title in sidebar",
                                    "required": False,
                                },
                            ),
                            7: (
                                "ov_collections.blocks.DurationBlock",
                                (),
                                {
                                    "help_text": "Start time for the media",
                                    "required": False,
                                },
                            ),
                            8: (
                                "ov_collections.blocks.DurationBlock",
                                (),
                                {
                                    "help_text": "End time for the media",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("all", "All"),
                                        ("digitized", "Digitized"),
                                        ("online", "Online"),
                                    ],
                                    "help_text": "Access level for AAPB search links in this block",
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("guids", 2),
                                        ("special_collections", 3),
                                        ("show_title", 4),
                                        ("show_thumbnail", 5),
                                        ("show_sidebar", 6),
                                        ("start_time", 7),
                                        ("end_time", 8),
                                        ("access_level", 9),
                                    ]
                                ],
                                {"icon": "doc-full-inverse"},
                            ),
                        },
                        help_text="Featured sources in the Source Set",
                    ),
                ),
            ],
            options={
                "verbose_name": "AAPB Primary Source Set",
                "verbose_name_plural": "AAPB Primary Source Sets",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AAPBPssRelatedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aapb_collections.aapbcollection",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_collections",
                        to="aapb_pss.aapbprimarysourceset",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AAPBPssRelatedExhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aapb_exhibits.aapbexhibit",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_exhibits",
                        to="aapb_pss.aapbprimarysourceset",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AAPBPssRelatedPrimarySourceSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_pss",
                        to="aapb_pss.aapbprimarysourceset",
                    ),
                ),
                (
                    "pss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aapb_pss.aapbprimarysourceset",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
