# Generated by Django 5.2.4 on 2025-08-01 21:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_exhibits", "__first__"),
        ("authors", "0004_alter_authorsorderable_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBAuthorsOrderable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="authors.author"
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="aapb_exhibits.aapbexhibit",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "author")},
            },
        ),
    ]
