# Generated by Django 5.2.8 on 2025-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0005_aapbauthorsorderable"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="title",
            field=models.CharField(
                blank=True, help_text="Author title", max_length=200
            ),
        ),
    ]
