# Generated by Django 4.2.8 on 2023-12-19 23:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("ov_collections", "0011_alter_collection_aapb_records_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="aapb_records",
        ),
        migrations.AlterField(
            model_name="collection",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "interviews",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="openquote",
                            label="Interview",
                        ),
                    ),
                    (
                        "archival_footage",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="form",
                            label="Footage",
                        ),
                    ),
                    (
                        "photographs",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="image",
                            label="Photograph",
                        ),
                    ),
                    (
                        "original_footage",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="doc-full-inverse",
                            label="Footage",
                        ),
                    ),
                    (
                        "programs",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="clipboard-list",
                            label="Program",
                        ),
                    ),
                    (
                        "related_content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "guids",
                                    wagtail.blocks.TextBlock(
                                        help_text="AAPB record IDs, separated by whitespace",
                                        required=True,
                                    ),
                                ),
                                (
                                    "show_title",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_thumbnail",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Show thumbnail",
                                        required=False,
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(
                                        features=["italic"],
                                        help_text="The title of this group",
                                        max_length=1024,
                                        required=False,
                                    ),
                                ),
                            ],
                            icon="list-ul",
                            label="Content",
                        ),
                    ),
                    ("credits", wagtail.blocks.RichTextBlock()),
                    (
                        "heading",
                        wagtail.blocks.RichTextBlock(
                            features=["italic"], form_classname="title"
                        ),
                    ),
                    ("text", wagtail.blocks.TextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
