# Generated by Django 4.2.8 on 2023-12-19 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ov_collections", "0012_alter_collection_aapb_records_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="aapb_records",
        ),
    ]
