# Generated by Django 5.2.3 on 2025-07-22 19:25

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ov_collections", "0020_collection_featured"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="page_ptr",
        ),
        migrations.CreateModel(
            name="CollectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
        migrations.AddField(
            model_name="collection",
            name="collectionpage_ptr",
            field=models.OneToOneField(
                auto_created=True,
                # default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="ov_collections.collectionpage",
            ),
            preserve_default=False,
        ),
    ]
