# Generated by Django 5.2.4 on 2025-07-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ov_collections", "0020_collection_featured"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="CollectionPage",
        ),
    ]
