# Generated by Django 5.2.4 on 2025-07-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ov_collections", "0021_rename_collection_collectionpage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollectionPage",
            new_name="OpenVaultCollection",
        ),
    ]
