# Generated by Django 5.2.4 on 2025-07-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ov_collections", "0022_rename_collectionpage_openvaultcollection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openvaultcollection",
            options={
                "verbose_name": "Open Vault Collection",
                "verbose_name_plural": "Open Vault Collections",
            },
        ),
    ]
