# Generated by Django 5.2.4 on 2025-07-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0018_alter_exhibitpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitpage",
            options={
                "verbose_name": "Open Vault Exhibit Page",
                "verbose_name_plural": "Open Vault Exhibit Pages",
            },
        ),
    ]
