# Generated by Django 5.2.4 on 2025-08-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0019_alter_exhibitpage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitpage",
            options={
                "verbose_name": "Open Vault Exhibit",
                "verbose_name_plural": "Open Vault Exhibits",
            },
        ),
    ]
