# Generated by Django 5.2.4 on 2025-08-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0004_alter_authorsorderable_author_and_more"),
        ("exhibits", "0020_alter_exhibitpage_options"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExhibitPage",
            new_name="OpenVaultExhibit",
        ),
    ]
