# Generated by Django 5.2.4 on 2025-08-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0021_rename_exhibitpage_openvaultexhibit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitsorderable",
            options={},
        ),
    ]
