# Generated by Django 5.2.8 on 2025-12-08 21:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0022_alter_exhibitsorderable_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvaultexhibit",
            name="display_title",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Use this field to override the page title as displayed (e.g., with italics).",
                null=True,
                verbose_name="Display Title",
            ),
        ),
    ]
