# Generated by Django 5.2.8 on 2026-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0024_alter_openvaultexhibit_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvaultexhibit",
            name="special_collections",
            field=models.TextField(
                blank=True,
                help_text="Special collections IDs, separated by whitespace",
                null=True,
            ),
        ),
    ]
