# Generated by Django 5.2.11 on 2026-06-23 17:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0025_openvaultexhibit_special_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openvaultexhibit",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("interviews", 10),
                    ("archival_footage", 11),
                    ("photographs", 12),
                    ("original_footage", 13),
                    ("programs", 14),
                    ("related_content", 15),
                    ("credits", 16),
                    ("heading", 17),
                    ("text", 18),
                    ("subheading", 17),
                    ("html", 19),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["italic"], "max_length": 1024, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "For use in Primary Source Sets Only",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "form_classname": "w-field--scrollable-textarea",
                            "help_text": "AAPB record ID, separated by whitespace if providing multiple IDs",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Special collections IDs", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset title(s) for this block",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset thumbnail(s) for this block",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Include title in sidebar",
                            "required": False,
                        },
                    ),
                    7: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "Start time for the media", "required": False},
                    ),
                    8: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "End time for the media", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("all", "All"),
                                ("digitized", "Digitized"),
                                ("online", "Online"),
                            ],
                            "help_text": "Access level for AAPB search links in this block",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "openquote", "label": "Interviews"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "clipboard-list", "label": "Archival Footage"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "copy", "label": "Photographs"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "doc-full-inverse", "label": "Original Footage"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "desktop", "label": "Programs"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "table", "label": "Related Content"},
                    ),
                    16: ("wagtail.blocks.RichTextBlock", (), {"icon": "form"}),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "form_classname": "title",
                            "icon": "title",
                        },
                    ),
                    18: ("exhibits.models.RichTextFootnotesBlock", (), {}),
                    19: ("wagtail.blocks.RawHTMLBlock", (), {"label": "HTML"}),
                },
            ),
        ),
    ]
