"""
Django settings for ov-wag project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# Build paths inside the project like this: path.join(BASE_DIR, ...)
from json import JSONDecodeError, dumps, loads
from os import path, environ as env

from dotenv import load_dotenv

# take environment variables from .env.
load_dotenv()

PROJECT_DIR = path.dirname(path.dirname(path.abspath(__file__)))
BASE_DIR = path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'home',
    'authors',
    'exhibits',
    'ov_collections',
    'ov_wag',
    'aapb_collections',
    'aapb_exhibits',
    'search',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.styleguide',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'wagtail.api.v2',
    'corsheaders',
    'rest_framework',
    'modelcluster',
    'taggit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_hosts',
    'wagtail_headless_preview',
    'wagtail.contrib.search_promotions',
    'wagtail_footnotes',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.auth0',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'ov_wag.middleware.DjangoHostsSiteMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

# django-hosts settings
ROOT_URLCONF = 'ov_wag.urls'
ROOT_HOSTCONF = 'ov_wag.hosts'
DEFAULT_HOST = env.get('DEFAULT_HOST', 'ov')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ov_wag.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASES = {
    'default': {
        'ENGINE': env.get('OV_DB_ENGINE', 'django.db.backends.postgresql'),
        'HOST': env.get('OV_DB_HOST'),
        'PORT': env.get('OV_DB_PORT'),
        'NAME': env.get('OV_DB_NAME'),
        'USER': env.get('OV_DB_USER'),
        'PASSWORD': env.get('OV_DB_PASSWORD'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # noqa: E501
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CORS to allow cross-origin requests from the client
CORS_ALLOW_ALL_ORIGINS = True
CORS_URLS_REGEX = r'^/api/v2/'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    path.join(PROJECT_DIR, 'static'),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_ROOT = path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings

WAGTAIL_SITE_NAME = 'Open Vault'

# Search
# https://docs.wagtail.io/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.elasticsearch8',
        'URLS': [env.get('ES_URL', 'https://localhost:9200')],
        'INDEX': env.get('ES_INDEX', 'wagtail'),
        'TIMEOUT': 5,
        'OPTIONS': {
            'verify_certs': env.get('ES_VERIFY_CERTS', 'true') == 'true',
            'basic_auth': [
                env.get('ES_USER', 'elastic'),
                env.get('ES_PASSWORD'),
            ],
        },
        'INDEX_SETTINGS': {},
    }
}

# URL settings

WAGTAIL_BASE_URL = env.get('OV_BASE_URL')
WAGTAILADMIN_BASE_URL = env.get('OV_ADMIN_BASE_URL', '')

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILAPI_BASE_URL = env.get('OV_API_URL')


# API settings

# TODO: Set this to a real limit once we create pagination for the frontend endpoints
WAGTAILAPI_LIMIT_MAX = None

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10**5

# Wagtail Headless Preview settings
# Set $PREVIEW_CLIENT_URLS to a JSON object mapping Wagtail site IDs to client URLs.
# See https://github.com/torchbox/wagtail-headless-preview#multi-site-setup for details.

try:
    client_urls = loads(
        env.get('PREVIEW_CLIENT_URLS', dumps({'default': WAGTAIL_BASE_URL}))
    )

    WAGTAIL_HEADLESS_PREVIEW = {
        'CLIENT_URLS': client_urls,
    }
except JSONDecodeError:
    print(
        'Warning: PREVIEW_CLIENT_URLS is not valid JSON. Preview URLs will not be set.'
    )


# OIDC Provider settings
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]
SOCIALACCOUNT_PROVIDERS = {
    'auth0': {
        'AUTH0_URL': env.get('AUTH0_URL'),
        'OAUTH_PKCE_ENABLED': True,
        'APP': {
            'client_id': env.get('AUTH0_CLIENT_ID'),
            'secret': env.get('AUTH0_CLIENT_SECRET'),
        },
    }
}
GOOGLE_CLIENT_ID = env.get('GOOGLE_CLIENT_ID')
LOGIN_CALLBACK_URL = WAGTAILADMIN_BASE_URL + '/auth0/login/callback/'
LOGIN_REDIRECT_URL = WAGTAILADMIN_BASE_URL + '/admin/'
