# Generated by Django 5.2.4 on 2025-07-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePage",
            new_name="OpenVaultHomePage",
        ),
    ]
