# Generated by Django 5.2.4 on 2025-07-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_homepage_openvaulthomepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openvaulthomepage",
            options={
                "verbose_name": "Open Vault Home Page",
                "verbose_name_plural": "Open Vault Home Pages",
            },
        ),
    ]
