#!/bin/bash

function help {
  echo "Usage: $0 <dump_file>"
  echo "Restores the OpenVocab database from a specified dump file."
  echo
  echo "Arguments:"
  echo "  <dump_file>   Path to the database dump file to restore."
}

# Restore the database from a dump file
if [ -z "$1" ]; then
  echo "Error: No dump file specified."
  help
  exit 1

fi
DUMP_FILE="$1"

if [ ! -f "$DUMP_FILE" ]; then
  echo "Dump file '$DUMP_FILE' does not exist."
  help
  exit 1
fi

psql "postgresql://$OV_DB_USER:$OV_DB_PASSWORD@$OV_DB_HOST:$OV_DB_PORT/$OV_DB_NAME" -f "$DUMP_FILE"
export PG_PASSWORD=$OV_DB_PASSWORD
# pg_restore -d $OV_DB_NAME -U $OV_DB_USER -h $OV_DB_HOST "$DUMP_FILE"
