#!/usr/bin/env bash

# This script updates the documentation version number to match the current application version.

# Get the current version number
VERSION=$(python -c 'from ov_wag._version import __version__;print(__version__)'| grep -oP '^\d+\.\d+')

# Get the latest version number from the documentation
DOCS_VERSION=$(mike list latest | grep -oP '^\d+\.\d+')


# echo "Current app version: $VERSION"
# echo "Current docs version: $DOCS_VERSION"

if [ "$VERSION" == "$DOCS_VERSION" ]; then
    echo "Documentation version is already up-to-date."
    exit 0
fi

# Update the version in the documentation
mike deploy -up $VERSION latest
if [ $? -ne 0 ]; then
    echo "Failed to update the documentation version."
    exit 1
fi
echo "Documentation version successfully updated to $VERSION."
