# Generated by Django 5.2.3 on 2025-07-22 19:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ov_collections", "0021_add_collection_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBCollection",
            fields=[
                (
                    "collectionpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ov_collections.collectionpage",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("background", 0),
                            ("featured", 1),
                            ("funders", 2),
                            ("help", 3),
                            ("terms", 0),
                            ("timeline", 4),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "doc-full-inverse"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {"icon": "star"}),
                            2: ("wagtail.blocks.RichTextBlock", (), {"icon": "group"}),
                            3: ("wagtail.blocks.RichTextBlock", (), {"icon": "help"}),
                            4: ("wagtail.blocks.RichTextBlock", (), {"icon": "clock"}),
                        },
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("date", "Date"),
                            ("random", "Random"),
                        ],
                        default="title",
                        help_text="Choose how to sort the collection items.",
                        max_length=8,
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        help_text="Choose the order of the sorted items.",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("ov_collections.collectionpage",),
        ),
    ]
