# Generated by Django 5.2.4 on 2025-07-23 20:04

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AAPBCollection",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("background", 0),
                            ("featured", 1),
                            ("funders", 2),
                            ("help", 3),
                            ("terms", 0),
                            ("timeline", 4),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "doc-full-inverse"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {"icon": "star"}),
                            2: ("wagtail.blocks.RichTextBlock", (), {"icon": "group"}),
                            3: ("wagtail.blocks.RichTextBlock", (), {"icon": "help"}),
                            4: ("wagtail.blocks.RichTextBlock", (), {"icon": "clock"}),
                        },
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("date", "Date"),
                            ("random", "Random"),
                        ],
                        default="title",
                        help_text="Choose how to sort the collection items.",
                        max_length=8,
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        help_text="Choose the order of the sorted items.",
                        max_length=4,
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
