# Generated by Django 5.2.4 on 2025-07-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0003_alter_aapbcollection_sort_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbcollection",
            name="sort_by",
            field=models.CharField(
                blank=True,
                choices=[("title", "Title"), ("date", "Date"), ("random", "Random")],
                default="title",
                help_text="Choose how to sort the collection items.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aapbcollection",
            name="sort_order",
            field=models.CharField(
                blank=True,
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="asc",
                help_text="Choose the order of the sorted items.",
                max_length=4,
                null=True,
            ),
        ),
    ]
