# Generated by Django 5.2.4 on 2025-07-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0004_alter_aapbcollection_sort_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aapbcollection",
            options={
                "verbose_name": "AAPB Collection",
                "verbose_name_plural": "AAPB Collections",
            },
        ),
    ]
