# Generated by Django 5.2.4 on 2025-07-25 17:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0005_alter_aapbcollection_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aapbcollection",
            name="display_title",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Use this field to override the page title as displayed (e.g., with italics).",
                verbose_name="Display Title",
            ),
        ),
    ]
