# Generated by Django 5.2.4 on 2025-07-31 22:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0006_aapbcollection_display_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbcollection",
            name="display_title",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Use this field to override the page title as displayed (e.g., with italics).",
                null=True,
                verbose_name="Display Title",
            ),
        ),
        migrations.AlterField(
            model_name="aapbcollection",
            name="featured_items",
            field=wagtail.fields.StreamField(
                [("records", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "AAPB record IDs, separated by whitespace",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Special collections IDs", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset title(s) for this block",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset thumbnail(s) for this block",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Include title in sidebar",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "help_text": "The title of this group",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    6: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "Start time for the group", "required": False},
                    ),
                    7: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "End time for the group", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("all", "All"),
                                ("digitized", "Digitized"),
                                ("online", "Online"),
                            ],
                            "help_text": "Access level for AAPB search links in this block",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("guids", 0),
                                ("special_collections", 1),
                                ("show_title", 2),
                                ("show_thumbnail", 3),
                                ("show_sidebar", 4),
                                ("title", 5),
                                ("start_time", 6),
                                ("end_time", 7),
                                ("access_level", 8),
                            ]
                        ],
                        {"icon": "doc-full-inverse"},
                    ),
                },
                help_text="Featured items in the collection",
            ),
        ),
    ]
