# Generated by Django 5.2.8 on 2026-01-07 20:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0007_alter_aapbcollection_display_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbcollection",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("background", 0),
                    ("funders", 1),
                    ("help", 2),
                    ("resources", 3),
                    ("terms", 4),
                    ("timeline", 5),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Collection Background"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "group"}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"icon": "help"}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Other Resources"},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse"},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {"icon": "clock"}),
                },
            ),
        ),
    ]
