# Generated by Django 5.2.11 on 2026-06-23 17:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0009_aapbcollection_special_collections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbcollection",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("background", 0),
                    ("funders", 1),
                    ("help", 2),
                    ("resources", 3),
                    ("terms", 4),
                    ("timeline", 5),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Collection Background"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "group"}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"icon": "help"}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Other Resources"},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Suggested Searches"},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {"icon": "clock"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="aapbcollection",
            name="featured_items",
            field=wagtail.fields.StreamField(
                [("records", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["italic"], "max_length": 1024, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "For use in Primary Source Sets Only",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "form_classname": "w-field--scrollable-textarea",
                            "help_text": "AAPB record ID, separated by whitespace if providing multiple IDs",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Special collections IDs", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset title(s) for this block",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show asset thumbnail(s) for this block",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Include title in sidebar",
                            "required": False,
                        },
                    ),
                    7: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "Start time for the media", "required": False},
                    ),
                    8: (
                        "ov_collections.blocks.DurationBlock",
                        (),
                        {"help_text": "End time for the media", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("all", "All"),
                                ("digitized", "Digitized"),
                                ("online", "Online"),
                            ],
                            "help_text": "Access level for AAPB search links in this block",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("guids", 2),
                                ("special_collections", 3),
                                ("show_title", 4),
                                ("show_thumbnail", 5),
                                ("show_sidebar", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("access_level", 9),
                            ]
                        ],
                        {"icon": "doc-full-inverse"},
                    ),
                },
                help_text="Featured items in the collection",
            ),
        ),
    ]
