# Generated by Django 5.2.11 on 2026-07-14 19:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aapb_collections", "0012_alter_aapbcollection_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aapbcollection",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("background", 0),
                    ("funders", 1),
                    ("help", 2),
                    ("resources", 3),
                    ("terms", 4),
                    ("timeline", 5),
                    ("vimeo", 8),
                    ("youtube", 9),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Collection Background"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"icon": "group"}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"icon": "help"}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Other Resources"},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full-inverse", "label": "Suggested Searches"},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {"icon": "clock"}),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "The URL of the video", "required": True},
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic"],
                            "help_text": "The title of this video",
                            "max_length": 1024,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 6), ("title", 7)]],
                        {"label": "Vimeo"},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 6), ("title", 7)]],
                        {"label": "YouTube"},
                    ),
                },
            ),
        ),
    ]
