name: 🧪 Integration Tests

on: [push, pull_request, merge_group, workflow_dispatch]

jobs:
  tests:
    name: ⚗️ App Tests
    uses: WGBH-MLA/ov-wag/.github/workflows/pytest-with-postgres.yml@main
    secrets: inherit
    with:
      pytest_args: -n auto --nbmake -ra -s
      pg_db: ov
  lint:
    name: 👕 Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@v1

  black:
    name: 🖤 Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@v1
