name: 🏛 Publish to PyPi
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 📦 Build package
    runs-on: ubuntu-latest
    steps:
      - name: 📰 Checkout
        uses: actions/checkout@v6

      - name: 🚚 Install dependencies
        run: pip install uv

      - name: 🏗️ Build package
        run: uv build

      - name: 🛫 Export build files
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist

  publish:
    name: 🗞 Publish package
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ov-wag
    permissions:
      id-token: write
    steps:
      - name: 🛬 Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: 🗞 Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
